spring.application.name=client-service
server.port=8081

app.io-service.base-url=${IO_SERVICE_BASE_URL:http://localhost:8083}
app.messaging.request-created-exchange=${REQUEST_CREATED_EXCHANGE:processing.exchange}
app.messaging.request-created-routing-key=${REQUEST_CREATED_ROUTING_KEY:request.created}

management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
